### ISSUE TITLE
isNatural function can not handle numbers in Scientific Notation Form

### ISSUE THREAD

**Issue by ShadowXBoss696** [Kode-Devs/package-libmath#1]
https://github.com/Kode-Devs/package-libmath/blob/48e0287d49f37487670ab9a96f617a5b94a6ba9d/libmath.kde#L11

Function `isNatural` works fine for `1e3` as String representation of `1e3` is _'1000'_.
```
>>> isNatural(1e3);
True
```

But for **larger values** whose String representation is of Scientific Notation Form, eg.- `1e30`
```
>>> isNatural(1e30);
False
```

Thanking You,
@Edumate696

**Comment by axen46** [comment]
Okay I will look into this matter.
