### ISSUE TITLE
Suggestion to use x>=0 instead of using ( x>0 or x==0 ) 

### ISSUE THREAD

**Issue by ShadowXBoss696** [Kode-Devs/package-libmath#2]
Dear Dev (@axen46),
I have a suggestion in respect to the below given portion of the `abs()` in your library. Please check it once.
https://github.com/Kode-Devs/package-libmath/blob/6a32c6ce56ddb8b5748a690162b01bb989106803/libmath.kde#L63

I do not understand why are you doing `x>0 or x==0` instead of `x>=0`, as per _Kode_ binary operations are equivalent to function call and thus may take twice the time than the former one. Thus, my reccomendation is to use the later one instead.

It will be very helpful if you provide some information regarding this issue.
Thanking You,
@Edumate696

**Comment by axen46** [comment]
Okay I get it. Thanks.

**Comment by ShadowXBoss696** [comment]
Thank You, and remember to close the issue when you have solved it ...
